# Generated by Django 5.2 on 2025-04-18 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('EVALUATING', 'Evaluating'), ('EVALUATED', 'Evaluated'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OUTSOURCED', 'Outsourced'), ('TRANSFERRED', 'Transferred to Central'), ('NEED_PARTS', 'Waiting for Parts'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='new_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('EVALUATING', 'Evaluating'), ('EVALUATED', 'Evaluated'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OUTSOURCED', 'Outsourced'), ('TRANSFERRED', 'Transferred to Central'), ('NEED_PARTS', 'Waiting for Parts'), ('REJECTED', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='old_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('EVALUATING', 'Evaluating'), ('EVALUATED', 'Evaluated'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OUTSOURCED', 'Outsourced'), ('TRANSFERRED', 'Transferred to Central'), ('NEED_PARTS', 'Waiting for Parts'), ('REJECTED', 'Rejected')], max_length=20),
        ),
        migrations.CreateModel(
            name='RepairEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('CAN_FIX', 'สามารถซ่อมได้'), ('OUTSOURCE', 'ต้องจ้างภายนอก'), ('CENTRAL_DEPT', 'ส่งกองกลาง'), ('NEED_PARTS', 'ต้องการอะไหล่ก่อนซ่อม')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_time', models.IntegerField(blank=True, help_text='Estimated time in hours', null=True)),
                ('parts_needed', models.TextField(blank=True, help_text='List of parts needed for repair')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='maintenance.maintenancerequest')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evaluation_images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maintenance.repairevaluation')),
            ],
        ),
    ]
