# Generated by Django 5.2 on 2025-04-18 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenancerequest_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceassignment',
            options={'ordering': ['-assigned_at'], 'permissions': [('can_assign_maintenance', 'Can assign maintenance requests to technicians')]},
        ),
        migrations.RenameField(
            model_name='maintenanceassignment',
            old_name='notes',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='maintenanceassignment',
            name='request',
        ),
        migrations.AddField(
            model_name='maintenanceassignment',
            name='assigned_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_assignments_made', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceassignment',
            name='maintenance_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='maintenance.maintenancerequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenanceassignment',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
