# Generated by Django 5.2 on 2025-04-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_approval_notification_statuslog_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
