# Generated by Django 5.2 on 2025-04-18 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_maintenanceassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceassignment',
            name='maintenance_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancerequest'),
        ),
        migrations.CreateModel(
            name='MaintenanceEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_duration', models.PositiveIntegerField(help_text='Estimated duration in days')),
                ('evaluation_note', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'ต่ำ'), ('MEDIUM', 'ปานกลาง'), ('HIGH', 'สูง'), ('URGENT', 'เร่งด่วน')], default='MEDIUM', max_length=10)),
                ('evaluated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_evaluations', to=settings.AUTH_USER_MODEL)),
                ('maintenance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='maintenance.maintenancerequest')),
            ],
            options={
                'ordering': ['-evaluated_at'],
                'permissions': [('can_evaluate_maintenance', 'Can evaluate maintenance requests')],
            },
        ),
    ]
