# Generated by Django 5.2 on 2025-04-17 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_notification_read_at_alter_notification_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='maintenance_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancerequest'),
        ),
    ]
