# Generated by Django 5.2 on 2025-04-17 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_notification_maintenance_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='maintenance_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='maintenance.maintenancerequest'),
        ),
        migrations.AlterField(
            model_name='maintenanceimage',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maintenance.maintenancerequest'),
        ),
    ]
