# Generated by Django 5.2 on 2025-04-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_maintenancerequest_approval_note_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaintenanceEvaluation',
        ),
    ]
