# Generated by Django 5.2 on 2025-04-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_alter_comment_maintenance_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='position',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_preferences',
            field=models.CharField(choices=[('ALL', 'รับการแจ้งเตือนทั้งหมด'), ('EMAIL', 'อีเมลเท่านั้น'), ('LINE', 'Line เท่านั้น'), ('NONE', 'ไม่รับการแจ้งเตือน')], default='ALL', max_length=10),
        ),
    ]
