# Generated by Django 5.2 on 2025-04-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_delete_maintenanceevaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='approval_note',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='approved_by',
        ),
    ]
