# Generated by Django 5.2 on 2025-04-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_repairevaluation_approved_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('LOW', 'ต่ำ'), ('MEDIUM', 'ปานกลาง'), ('HIGH', 'สูง'), ('URGENT', 'เร่งด่วน')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('ASSIGNED', 'มอบหมายแล้ว'), ('EVALUATING', 'กำลังประเมิน'), ('EVALUATED', 'ประเมินแล้ว'), ('APPROVED', 'อนุมัติแล้ว'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('COMPLETED', 'เสร็จสมบูรณ์'), ('OUTSOURCED', 'จ้างภายนอก'), ('TRANSFERRED', 'ส่งต่อไปส่วนกลาง'), ('NEED_PARTS', 'รออะไหล่'), ('REJECTED', 'ปฏิเสธ')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='new_status',
            field=models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('ASSIGNED', 'มอบหมายแล้ว'), ('EVALUATING', 'กำลังประเมิน'), ('EVALUATED', 'ประเมินแล้ว'), ('APPROVED', 'อนุมัติแล้ว'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('COMPLETED', 'เสร็จสมบูรณ์'), ('OUTSOURCED', 'จ้างภายนอก'), ('TRANSFERRED', 'ส่งต่อไปส่วนกลาง'), ('NEED_PARTS', 'รออะไหล่'), ('REJECTED', 'ปฏิเสธ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='old_status',
            field=models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('ASSIGNED', 'มอบหมายแล้ว'), ('EVALUATING', 'กำลังประเมิน'), ('EVALUATED', 'ประเมินแล้ว'), ('APPROVED', 'อนุมัติแล้ว'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('COMPLETED', 'เสร็จสมบูรณ์'), ('OUTSOURCED', 'จ้างภายนอก'), ('TRANSFERRED', 'ส่งต่อไปส่วนกลาง'), ('NEED_PARTS', 'รออะไหล่'), ('REJECTED', 'ปฏิเสธ')], max_length=20),
        ),
    ]
