# Generated by Django 5.2 on 2025-04-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_alter_maintenancerequest_priority_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletionImage',
        ),
    ]
