# Generated by Django 5.2 on 2025-04-20 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_delete_completionimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่ออะไหล่')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('part_number', models.CharField(blank=True, max_length=50, verbose_name='รหัสอะไหล่')),
                ('unit', models.CharField(default='ชิ้น', max_length=50, verbose_name='หน่วยนับ')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาต่อหน่วย')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='จำนวนในคลัง')),
                ('minimum_stock', models.IntegerField(default=0, verbose_name='จำนวนขั้นต่ำที่ควรมี')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'อะไหล่',
                'verbose_name_plural': 'อะไหล่',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อผู้ขาย')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='ชื่อผู้ติดต่อ')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='เบอร์โทรศัพท์')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='เลขประจำตัวผู้เสียภาษี')),
                ('is_active', models.BooleanField(default=True, verbose_name='สถานะ')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
            ],
            options={
                'verbose_name': 'ผู้ขาย',
                'verbose_name_plural': 'ผู้ขาย',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=20, unique=True, verbose_name='เลขที่ใบรับสินค้า')),
                ('received_date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่รับสินค้า')),
                ('delivery_note', models.CharField(blank=True, max_length=100, verbose_name='เลขที่ใบส่งของ')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='เลขที่ใบแจ้งหนี้')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับสินค้า')),
            ],
            options={
                'verbose_name': 'ใบรับสินค้า',
                'verbose_name_plural': 'ใบรับสินค้า',
            },
        ),
        migrations.CreateModel(
            name='POItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='จำนวน')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย')),
                ('received_quantity', models.IntegerField(default=0, verbose_name='จำนวนที่รับแล้ว')),
                ('is_fully_received', models.BooleanField(default=False, verbose_name='รับครบแล้ว')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.part', verbose_name='อะไหล่')),
            ],
            options={
                'verbose_name': 'รายการในใบสั่งซื้อ',
                'verbose_name_plural': 'รายการในใบสั่งซื้อ',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='จำนวนที่รับ')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.goodsreceipt', verbose_name='ใบรับสินค้า')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='maintenance.poitem', verbose_name='รายการในใบสั่งซื้อ')),
            ],
            options={
                'verbose_name': 'รายการในใบรับสินค้า',
                'verbose_name_plural': 'รายการในใบรับสินค้า',
            },
        ),
        migrations.CreateModel(
            name='PRItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='จำนวน')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.part', verbose_name='อะไหล่')),
            ],
            options={
                'verbose_name': 'รายการในใบขอซื้อ',
                'verbose_name_plural': 'รายการในใบขอซื้อ',
            },
        ),
        migrations.AddField(
            model_name='poitem',
            name='pr_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.pritem', verbose_name='รายการจากใบขอซื้อ'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=20, unique=True, verbose_name='เลขที่ PO')),
                ('status', models.CharField(choices=[('DRAFT', 'แบบร่าง'), ('ISSUED', 'ออกใบสั่งซื้อแล้ว'), ('PARTIAL', 'รับมอบบางส่วน'), ('RECEIVED', 'รับมอบครบแล้ว'), ('COMPLETED', 'เสร็จสมบูรณ์'), ('CANCELLED', 'ยกเลิก')], default='DRAFT', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่ออกใบสั่งซื้อ')),
                ('expected_delivery', models.DateField(blank=True, null=True, verbose_name='วันที่คาดว่าจะได้รับ')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='จำนวนเงินรวม')),
                ('vat_percent', models.DecimalField(decimal_places=2, default=7.0, max_digits=5, verbose_name='ภาษีมูลค่าเพิ่ม %')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='จำนวนภาษีมูลค่าเพิ่ม')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดรวมทั้งสิ้น')),
                ('payment_terms', models.CharField(blank=True, max_length=200, verbose_name='เงื่อนไขการชำระเงิน')),
                ('delivery_terms', models.TextField(blank=True, verbose_name='เงื่อนไขการส่งมอบ')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_pos', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อนุมัติ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pos', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
            ],
            options={
                'verbose_name': 'ใบสั่งซื้อ',
                'verbose_name_plural': 'ใบสั่งซื้อ',
                'permissions': [('issue_po', 'Can issue purchase orders'), ('receive_po', 'Can receive goods for purchase orders')],
            },
        ),
        migrations.AddField(
            model_name='poitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.purchaseorder', verbose_name='ใบสั่งซื้อ'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='maintenance.purchaseorder', verbose_name='ใบสั่งซื้อ'),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.CharField(max_length=20, unique=True, verbose_name='เลขที่ PR')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('priority', models.CharField(choices=[('LOW', 'ต่ำ'), ('MEDIUM', 'ปานกลาง'), ('HIGH', 'สูง'), ('URGENT', 'เร่งด่วน')], default='MEDIUM', max_length=10, verbose_name='ความเร่งด่วน')),
                ('department', models.CharField(max_length=100, verbose_name='แผนก')),
                ('status', models.CharField(choices=[('DRAFT', 'แบบร่าง'), ('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('REJECTED', 'ปฏิเสธ'), ('CONVERTED', 'แปลงเป็น PO แล้ว')], default='DRAFT', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่อนุมัติ')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='เหตุผลที่ปฏิเสธ')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='จำนวนเงินรวม')),
                ('budget_code', models.CharField(blank=True, max_length=50, verbose_name='รหัสงบประมาณ')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_prs', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อนุมัติ')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.repairevaluation', verbose_name='ผลการประเมิน')),
                ('maintenance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='maintenance.maintenancerequest', verbose_name='งานซ่อม')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขอซื้อ')),
            ],
            options={
                'verbose_name': 'ใบขอซื้อ',
                'verbose_name_plural': 'ใบขอซื้อ',
                'permissions': [('approve_pr', 'Can approve purchase requests'), ('reject_pr', 'Can reject purchase requests')],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='maintenance.purchaserequest', verbose_name='ใบขอซื้อ'),
        ),
        migrations.AddField(
            model_name='pritem',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.purchaserequest', verbose_name='ใบขอซื้อ'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.vendor', verbose_name='ผู้ขาย'),
        ),
    ]
