# Generated by Django 5.2 on 2025-04-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_part_vendor_goodsreceipt_poitem_goodsreceiptitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsrequest',
            name='part',
        ),
        migrations.RemoveField(
            model_name='partsrequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='partsrequest',
            name='maintenance_request',
        ),
        migrations.AlterField(
            model_name='repairevaluation',
            name='result',
            field=models.CharField(choices=[('CAN_FIX', 'ซ่อมได้เอง'), ('OUTSOURCE', 'จ้างภายนอก'), ('CENTRAL_DEPT', 'ช่างกองกลาง'), ('NEED_PARTS', 'ซ่อมได้ (ต้องการอะไหล่)')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Parts',
        ),
        migrations.DeleteModel(
            name='PartsRequest',
        ),
    ]
