# Generated by Django 5.2 on 2025-04-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_remove_partsrequest_part_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancecategory',
            options={'verbose_name': 'หมวดหมู่งานซ่อมบำรุง', 'verbose_name_plural': 'หมวดหมู่งานซ่อมบำรุง'},
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='department',
        ),
        migrations.AlterField(
            model_name='maintenancecategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='maintenancecategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='สถานะใช้งาน'),
        ),
        migrations.AlterField(
            model_name='maintenancecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่'),
        ),
    ]
