# Generated by Django 5.2 on 2025-04-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_alter_maintenancecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'permissions': [('change_status', 'Can change maintenance status')]},
        ),
    ]
