# Generated by Django 5.2 on 2025-04-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_alter_maintenancerequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('ASSIGNED', 'มอบหมายแล้ว'), ('EVALUATING', 'กำลังประเมิน'), ('EVALUATED', 'ประเมินแล้ว'), ('APPROVED', 'อนุมัติแล้ว'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('COMPLETED', 'เสร็จสมบูรณ์'), ('OUTSOURCED', 'จ้างภายนอก'), ('TRANSFERRED', 'ส่งต่อไปส่วนกลาง'), ('TRANSFERRED_PARTS', 'ส่งต่อไปส่วนกลาง (ต้องการอะไหล่)'), ('NEED_PARTS', 'รออะไหล่'), ('PR_DRAFT', 'กำลังทำใบขอซื้อ'), ('PR_PENDING', 'รออนุมัติใบขอซื้อ'), ('PR_APPROVED', 'อนุมัติใบขอซื้อแล้ว'), ('PO_CREATED', 'สร้างใบสั่งซื้อแล้ว'), ('WAITING_DELIVERY', 'รอรับอะไหล่'), ('PARTS_RECEIVED', 'ได้รับอะไหล่แล้ว'), ('REJECTED', 'ปฏิเสธ')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='repairevaluation',
            name='result',
            field=models.CharField(choices=[('CAN_FIX', 'ซ่อมได้เอง'), ('OUTSOURCE', 'จ้างภายนอก'), ('CENTRAL_DEPT', 'ช่างกองกลาง'), ('CENTRAL_DEPT_PARTS', 'ช่างกองกลาง (ต้องการอะไหล่)'), ('NEED_PARTS', 'ซ่อมได้ (ต้องการอะไหล่)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='new_status',
            field=models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('ASSIGNED', 'มอบหมายแล้ว'), ('EVALUATING', 'กำลังประเมิน'), ('EVALUATED', 'ประเมินแล้ว'), ('APPROVED', 'อนุมัติแล้ว'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('COMPLETED', 'เสร็จสมบูรณ์'), ('OUTSOURCED', 'จ้างภายนอก'), ('TRANSFERRED', 'ส่งต่อไปส่วนกลาง'), ('TRANSFERRED_PARTS', 'ส่งต่อไปส่วนกลาง (ต้องการอะไหล่)'), ('NEED_PARTS', 'รออะไหล่'), ('PR_DRAFT', 'กำลังทำใบขอซื้อ'), ('PR_PENDING', 'รออนุมัติใบขอซื้อ'), ('PR_APPROVED', 'อนุมัติใบขอซื้อแล้ว'), ('PO_CREATED', 'สร้างใบสั่งซื้อแล้ว'), ('WAITING_DELIVERY', 'รอรับอะไหล่'), ('PARTS_RECEIVED', 'ได้รับอะไหล่แล้ว'), ('REJECTED', 'ปฏิเสธ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='old_status',
            field=models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('ASSIGNED', 'มอบหมายแล้ว'), ('EVALUATING', 'กำลังประเมิน'), ('EVALUATED', 'ประเมินแล้ว'), ('APPROVED', 'อนุมัติแล้ว'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('COMPLETED', 'เสร็จสมบูรณ์'), ('OUTSOURCED', 'จ้างภายนอก'), ('TRANSFERRED', 'ส่งต่อไปส่วนกลาง'), ('TRANSFERRED_PARTS', 'ส่งต่อไปส่วนกลาง (ต้องการอะไหล่)'), ('NEED_PARTS', 'รออะไหล่'), ('PR_DRAFT', 'กำลังทำใบขอซื้อ'), ('PR_PENDING', 'รออนุมัติใบขอซื้อ'), ('PR_APPROVED', 'อนุมัติใบขอซื้อแล้ว'), ('PO_CREATED', 'สร้างใบสั่งซื้อแล้ว'), ('WAITING_DELIVERY', 'รอรับอะไหล่'), ('PARTS_RECEIVED', 'ได้รับอะไหล่แล้ว'), ('REJECTED', 'ปฏิเสธ')], max_length=20),
        ),
    ]
