# Generated by Django 5.2 on 2025-04-21 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_alter_maintenancerequest_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-created_at'], 'permissions': [('change_status', 'Can change maintenance status')]},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'permissions': [('issue_po', 'Can issue purchase orders'), ('receive_purchaseorder', 'Can receive goods for purchase orders')], 'verbose_name': 'ใบสั่งซื้อ', 'verbose_name_plural': 'ใบสั่งซื้อ'},
        ),
    ]
